# Generated by Django 4.2.1 on 2023-05-29 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clothes',
            options={'verbose_name': 'Мерч', 'verbose_name_plural': 'Мерч'},
        ),
        migrations.AddField(
            model_name='clothes',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
